version: "3.8"

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    depends_on:
      # 等待前端程序启动
      - fd-front
      - fd-backend
    container_name: reverse-proxy
  fd-backend:
    image: flight-diary-backend
    build:
      context: ./flight-diary
      dockerfile: dev.Dockerfile
    volumes:
      - ./flight-diary:/usr/src/app
    ports:
      - 3001:3001
    container_name: flight-diary-backend
  fd-front:
    image: flight-diary-front
    build:
      context: ./flight-diary-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./flight-diary-frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: flight-diary-front
