version: "3.8"

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    depends_on:
      # 等待前端程序启动
      - fd-front-prod
      - fd-backend-prod
    container_name: reverse-proxy
  fd-backend-prod:
    image: flight-diary-backend-prod
    build:
      context: ./flight-diary
      dockerfile: Dockerfile
    volumes:
      - ./flight-diary:/usr/src/app
    ports:
      - 3001:3001
    container_name: flight-diary-backend-prod
  fd-front-prod:
    image: flight-diary-front-prod
    build:
      context: ./flight-diary-frontend
      dockerfile: Dockerfile
    volumes:
      - ./flight-diary-frontend:/usr/src/app
    ports:
      - 8082:80
    container_name: flight-diary-front-prod
